version: "3"

networks:
    skyscan:
      driver: bridge
      driver_opts:
        com.docker.network.driver.mtu: 900

services:

  mqtt:
    networks:
      - skyscan
    image: iqtlabs/edgetech-mqtt-dev:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"

  ledger:
    networks:
      - skyscan
    build:
      context: ./ledger/object-ledger
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
      - object-ledger.env

  controller:
    networks:
      - skyscan
    build:
      context: ./controller/axis-ptz-controller
      dockerfile: Dockerfile
    volumes:
      - ./data/to_sort:/data/to_sort
    restart: unless-stopped
    depends_on:
      - mqtt
    env_file:
      - .env
      - axis-ptz-controller.env

  piaware:
    networks:
      - skyscan
    image: mikenye/piaware:latest
    tty: true
    container_name: piaware
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 8080:80
      - 30003:30003
      - 30005:30005
    restart: unless-stopped
    env_file:
      - .env
      - piaware.env

  dump1090-json:
    networks:
      - skyscan
    build:
      context: ./dump1090-json/dump1090-json
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on: 
      - mqtt
      - piaware
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    env_file:
      - .env
      - ./dump1090-json.env

  skyscan-c2:
    networks:
      - skyscan
    build:
      context: ./skyscan-c2/skyscan-c2
      dockerfile: Dockerfile
    volumes:
      - ./data/mapping:/data/mapping
    restart: unless-stopped
    depends_on:
      - mqtt
      - ledger
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    env_file:
      - .env
      - skyscan-c2.env

  console:
    networks:
      - skyscan
    build:
      context: ./console
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:5555"
    env_file:
      - .env
      - console.env


  manager:
    networks:
      - skyscan
    build:
      context: ./manager
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env

  # occlusion-mapper:
  #   networks:
  #     - skyscan
  #   image: iqtlabs/edgetech-occlusion-mapper:v1.0
  #   volumes:
  #     - ./data/mapping:/data/mapping
  #   ports:
  #     - "5000:5000"
  #   restart: unless-stopped
  #   depends_on:
  #     - mqtt
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10M"
  #       max-file: "10"
  #   env_file:
  #     - .env
